# Generated by Django 3.0.3 on 2021-01-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacherdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('teachers', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('desgination', models.CharField(max_length=255)),
                ('attendance', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
