# Generated by Django 3.0.3 on 2021-02-23 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0003_auto_20210223_1312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancetb',
            old_name='t_id',
            new_name='t',
        ),
    ]
