# Generated by Django 3.0.3 on 2021-02-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0005_auto_20210224_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancetb',
            name='status',
            field=models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], default='ABSENT', max_length=255),
        ),
    ]
