# Generated by Django 3.0.3 on 2021-03-10 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceapp', '0006_auto_20210224_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancetb',
            name='status',
            field=models.CharField(max_length=255),
        ),
    ]
